name = "CIF_dREL"
uuid = "828e923e-3bcf-11e9-1efc-b9e921b3bbf6"
authors = ["James.Hester <jxh@ansto.gov.au>"]
version = "0.1.0"

[deps]
CrystalInfoFramework = "6007d9b0-c6b2-11e8-0510-1d10e825f3f1"
DataContainer = "68b4d804-f79d-4e5f-bef9-7e30fa1fd457"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Lerche = "d42ef402-04e6-4356-9f73-091573ea58dc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
CrystalInfoFramework = "0.1.0"
Lerche = "0.1.0"
julia = "1.2"
