name: Build Documentation

on: [push, pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env: 
      LD_LIBRARY_PATH: ${{ github.workspace }}/lib:/usr/lib:/lib:/lib64
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
      DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
    steps: 
      - uses: actions/checkout@v2
      - uses: jamesrhester/CrystalInfoFramework.jl/.github/actions/cifapi_action@master
      - uses: julia-actions/setup-julia@latest
        with:
           version: '1.5'
      - name: Generate documentation
        run: |
           julia --project -e 'using Pkg; Pkg.instantiate()'
           julia --project docs/make.jl  
